[package]
name = "maria"
version = "0.1.0"
edition = "2021"

[dependencies]
pfg = { git = "https://github.com/andynet/pfg", branch = "main"}
clap = { version = "4.2.7", features = ["derive"] }
gfa = "0.10.1"
nom = "7.1.3"

[dev-dependencies]
proptest = "1.2.0"
